### ISSUE TITLE
Provide an alternate fallback aggregator/service if ODU MemGator is down

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#201]
Per @ibnesayeed

**Comment by machawk1** [comment]
Setup aggregator.matkelly.com for an off-site deployment of MemGator.

**Comment by machawk1** [comment]
aggregator.matkelly.com no longer hosts an instance. In February 2020 ODU had a DNS issue due to its ISP (I believe, Cox) that caused most things within *.odu.edu inclusive of the ODUCS MemGator endpoint to become inaccessible. No default fallback prevented Mink from receiving results.

There ought to be a fallback if no response from ODUCS MemGator after a certain time period. A model similar to MemGator's internal archive querying model of _sleeping_ a source if no response or an error would be fitting. We can't expect end-users to change their settings when the endpoint is inaccessible, so it MUST be fairly transparent and seamless.

@ibnesayeed I would very much like to know your thoughts on this given your involvement (i.e., creator) of MemGator and role in the ODUCS deployment instance.

**Comment by ibnesayeed** [comment]
Having a fallback or two is a good idea. If you are not relying on MemGator-specific features then LANL's TimeTravel service would be a good fallback. Alternatively, someone needs to run and maintain a service somewhere.

As far as automatic switching of endpoint is concerned, you can either perform a periodic health check (which can be noisy, if many independent installs of Mink are doing the same on a short regular interval) or passively try a fallback in case a network failure is detected when reaching the primary aggregator.

**Comment by machawk1** [comment]
@ibnesayeed From what I have seen, the LANL aggregator puts precedence to the DIY TMs (list of URI-Ts), which are not as useful to Mink as needing a TM with URI-Ms. Despite this, some further logic would be needed to "chase down" the TMs and perform aggregation from the client side. This moves more toward the direction of a client-side browser-based (JS) aggregator, which I hope to eventually implement if someone else does not first.

I believe some care is needed for Mink to re-enable the primary aggregator when it is accessible again. Does MemGator use a _k_ failures to sleep method? What is the basis for re-enabling a source that has gone dormant/failing? I will need to re-look at the MemGator code but hope you can provide some further direction.

**Comment by ibnesayeed** [comment]
MemGator tracks number of successive failures of each archive (and resets corresponding counter on a success response form an archive). It activates dormant state for an archive after a configurable number of successive failures. After waiting for a configurable period of time, it resets the failure count for that archive and marks it active. If the issue is not rectified then the dormant state will be triggered again after successive failures as before and the process will repeat. See the code below to understand the process:

https://github.com/oduwsdl/MemGator/blob/74213c9b6c31d9c741aaf2ef954c777941bbbee7/main.go#L288-L304

Reactivation happens by the virtue of a goroutine that is a lightweight thread which is spin off from the main thread, but sleeps for the dormant duration before it makes any state changes to bring the archive back to the active state.

**Comment by machawk1** [comment]
As of June 13-ish, 2021 ODUCS is down inclusive of the MemGator instance, which has rendered the production version of Mink non-functional, as memgator.cs.odu.edu times out. This is an easy fix and implemented as a fallback in a branch (where?) but needs to be deployed to the Chrome store.

Additionally, we should be able to mock tests to exhibit this behavior, which has occurred a few times and will make the tool more robust.
