### ISSUE TITLE
Error on a mediawiki instance

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#215]
Mink version 2.3
Visiting http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms causes Mink to display a "0" mementos badge. When the Mink icon is clicked, the "Archive webpage" interface is displayed. 

This is odd, @N0taN3rd, since we tested this exact wiki but a different page on Friday. The difference might be that there are 0 mementos of this wiki page and there were >0 for the other page we tested. Regardless, the red icon should be shown by Mink and no numerical badge.

![screen shot 2016-04-19 at 3 45 43 pm](https://cloud.githubusercontent.com/assets/2514780/14653228/fe2d850c-0645-11e6-8f7c-c56ba500de05.png)

**Comment by machawk1** [comment]
Via further investigation beyond @N0taN3rd's comments:

`curl -I http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms`

has a TG entry: http://timetravel.mementoweb.org/mediawiki/timegate/http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms

...but no TM.

`curl -I http://timetravel.mementoweb.org/mediawiki/timegate/http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms`
...results in a Link header with a `rel="original"` and `rel="memento"` but no TimeMap.

Mink is likely being tripped up on the lack of TimeMap specification.

@shawnmjones: Is this an atypical use case? Should a query to a TG result in a single memento and not a TM listing? I would expect a TM with a single memento.

/cc @phonedude

**Comment by phonedude** [comment]
looking at the tables in the appendix: https://tools.ietf.org/html/rfc7089#appendix-A
(and the wiki is pattern 1.1), TGs don't have to point to TMs, Ms don't have to point to TMs.  all values are ">=0"

**Comment by machawk1** [comment]
@N0taN3rd It might be useful to generate with a static set (e.g. web service) of TG/TM/M relations to simulate the patterns in the RFC. Such a set would also be useful for other tools. Keeping it static (i.e., no new mementos) would ensure that any tests that include a memCount === 0 are not tainted.

@phonedude Thanks for the pointer and clarification. Are you aware of any system to comprehensively tests Memento clients per above?

**Comment by phonedude** [comment]
There's the validator for server-side stuff: http://mementoweb.org/tools/validator/
but I'm not aware of an equivalent client-side validator.  That would be a neat tool/service.

**Comment by N0taN3rd** [comment]
@machawk1I agree this tool would be very useful.  Will be directing efforts to this tool using [rfc7089](https://tools.ietf.org/rfc/rfc7089.txt) as the gold standard.  Thank you as well @phonedude for the clarification

**Comment by shawnmjones** [comment]
Thanks also for the assist @phonedude.

For additional clarification: we have multiple MediaWiki instances installed on ws-dl-05.cs.odu.edu for testing and demonstration of the two different Memento MediaWiki Extensions.

The full Memento MediaWiki Extension at /demo/ supplies the TimeMap URI because it creates TimeMaps and thus knows their URI. Mink appears to work correctly with the full extension, correctly giving 59 mementos for http://ws-dl-05.cs.odu.edu/demo/index.php/Seven_Kingdoms.

The MementoHeaders extension runs at /demo-headers/ and can only supply a TimeGate URI because it does not create TimeMaps and there is no way for it to know which TimeMaps service it. Thus Mink finds 0 mementos for http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms.

I hope this helps.

**Comment by machawk1** [comment]
@shawnmjones Thank you for the further clarification.

Given that `curl -I http://timetravel.mementoweb.org/mediawiki/timegate/http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms` shows a [single memento](http://ws-dl-05.cs.odu.edu/demo-headers/index.php?title=Seven_Kingdoms&oldid=107221) in the Link header, is the correct answer to "How many mementos does `http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms` have?" 1 despite no TM being present?

Mink reports 0 but that's because it's currently setup to look for and parse TMs. Also, the UI for having 0 mementos is incorrect but that's a separate issue.

**Comment by shawnmjones** [comment]
@machawk1 

I spoke with the developer of the Memento MediaWiki proxy at timetravel.mementoweb.org and discovered the following for this TimeGate implementation:
* this single memento supplied in the Link header is always the same memento from the Location header
* this memento relation also contains the datetime for that memento so that a client does not need to perform a subsequent `HEAD` request to merely get that memento's Memento-Datetime

The correct answer to "How many mementos does `http://ws-dl-05.cs.odu.edu/demo-headers/index.php/Seven_Kingdoms` have?" is indeed 59 for this wiki, but neither the proxy nor the MementoHeaders MediaWiki Extension have any way of conveying this information.

If possible, in cases where no TimeMap is supplied, could Mink fall back to something like the TimeTravel API service (http://timetravel.mementoweb.org/guide/api/#timemap)? It will likely produce 0 mementos for this URI, but would provide a useful fallback for other URIs. At least Mink would get an answer from some authoritative source.

**Comment by machawk1** [comment]
@shawnmjones Good to know that `location` value is same as that defined in `Link`.

If a URI specifies its own TG, I would think that this specification is _the_ authoritative source on captures, even if some captures exist in other archives. By default, Mink queries a Memento aggregator for results and only goes down the path of follow-the-TG/TM if it is defined by the live web URI, which I believe is a relatively rare occurance on the live web.

Despite this, were Mink to report 0/1 memento(s) for a site that returned only an `original` and `memento` (like the wiki URI in question) instead of a TM when being dereferenced, supplying the user an option to archive the page (as Mink offers) would not change this number on reloading the URI-R.  We might be best off firing a request to both the aggregator and the TG specified by the URI simultaneously, comparing (and potentially even merging) the results, and return the more comprehensive count to the user. Given that specification of a TG is rare, subsequent requests for sites that specify their own could be quickly short circuited, allowing the base logic of querying the aggregator to run.

Thanks for the feedback and further investigation.
